// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Sampling mode for generation
enum SamplingModeType: Int {
  case greedy = 0
  case topK = 1
  case topP = 2
}

/// Use case for the model
enum ModelUseCaseType: Int {
  case general = 0
  case contentTagging = 1
}

/// Guardrails setting for the model
enum ModelGuardrailsType: Int {
  case defaultGuardrails = 0
  case permissiveContentTransformations = 1
}

/// Generation error types matching Swift's LanguageModelSession.GenerationError
enum GenerationErrorType: Int {
  case exceededContextWindowSize = 0
  case assetsUnavailable = 1
  case guardrailViolation = 2
  case unsupportedGuide = 3
  case unsupportedLanguageOrLocale = 4
  case decodingFailure = 5
  case rateLimited = 6
  case concurrentRequests = 7
  case refusal = 8
  case unknown = 9
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolDefinitionMessage {
  var name: String
  var description: String
  var parameters: [String?: Any?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolDefinitionMessage? {
    let name = pigeonVar_list[0] as! String
    let description = pigeonVar_list[1] as! String
    let parameters = pigeonVar_list[2] as! [String?: Any?]

    return ToolDefinitionMessage(
      name: name,
      description: description,
      parameters: parameters
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      description,
      parameters,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SamplingModeMessage {
  var type: SamplingModeType
  var topK: Int64? = nil
  var probabilityThreshold: Double? = nil
  var seed: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SamplingModeMessage? {
    let type = pigeonVar_list[0] as! SamplingModeType
    let topK: Int64? = nilOrValue(pigeonVar_list[1])
    let probabilityThreshold: Double? = nilOrValue(pigeonVar_list[2])
    let seed: Int64? = nilOrValue(pigeonVar_list[3])

    return SamplingModeMessage(
      type: type,
      topK: topK,
      probabilityThreshold: probabilityThreshold,
      seed: seed
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      topK,
      probabilityThreshold,
      seed,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GenerationOptionsMessage {
  var sampling: SamplingModeMessage? = nil
  var temperature: Double? = nil
  var maximumResponseTokens: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationOptionsMessage? {
    let sampling: SamplingModeMessage? = nilOrValue(pigeonVar_list[0])
    let temperature: Double? = nilOrValue(pigeonVar_list[1])
    let maximumResponseTokens: Int64? = nilOrValue(pigeonVar_list[2])

    return GenerationOptionsMessage(
      sampling: sampling,
      temperature: temperature,
      maximumResponseTokens: maximumResponseTokens
    )
  }
  func toList() -> [Any?] {
    return [
      sampling,
      temperature,
      maximumResponseTokens,
    ]
  }
}

/// Configuration for creating a model
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelConfigurationMessage {
  /// Internal adapter ID (from adapters map on Swift side)
  var adapterId: String? = nil
  var useCase: ModelUseCaseType? = nil
  var guardrails: ModelGuardrailsType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelConfigurationMessage? {
    let adapterId: String? = nilOrValue(pigeonVar_list[0])
    let useCase: ModelUseCaseType? = nilOrValue(pigeonVar_list[1])
    let guardrails: ModelGuardrailsType? = nilOrValue(pigeonVar_list[2])

    return ModelConfigurationMessage(
      adapterId: adapterId,
      useCase: useCase,
      guardrails: guardrails
    )
  }
  func toList() -> [Any?] {
    return [
      adapterId,
      useCase,
      guardrails,
    ]
  }
}

/// Message for creating an adapter
///
/// Generated class from Pigeon that represents data sent in messages.
struct AdapterMessage {
  var adapterId: String
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdapterMessage? {
    let adapterId = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String

    return AdapterMessage(
      adapterId: adapterId,
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      adapterId,
      name,
    ]
  }
}

/// Model availability status
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelAvailabilityMessage {
  var isAvailable: Bool
  var unavailableReason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelAvailabilityMessage? {
    let isAvailable = pigeonVar_list[0] as! Bool
    let unavailableReason: String? = nilOrValue(pigeonVar_list[1])

    return ModelAvailabilityMessage(
      isAvailable: isAvailable,
      unavailableReason: unavailableReason
    )
  }
  func toList() -> [Any?] {
    return [
      isAvailable,
      unavailableReason,
    ]
  }
}

/// Generation error with type and context
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerationErrorMessage {
  var type: GenerationErrorType
  var message: String
  var debugDescription: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationErrorMessage? {
    let type = pigeonVar_list[0] as! GenerationErrorType
    let message = pigeonVar_list[1] as! String
    let debugDescription: String? = nilOrValue(pigeonVar_list[2])

    return GenerationErrorMessage(
      type: type,
      message: message,
      debugDescription: debugDescription
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      message,
      debugDescription,
    ]
  }
}

/// Response from text generation
///
/// Generated class from Pigeon that represents data sent in messages.
struct TextResponseMessage {
  /// The generated text content
  var content: String
  /// JSON-encoded transcript entries from this response
  var transcriptJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TextResponseMessage? {
    let content = pigeonVar_list[0] as! String
    let transcriptJson = pigeonVar_list[1] as! String

    return TextResponseMessage(
      content: content,
      transcriptJson: transcriptJson
    )
  }
  func toList() -> [Any?] {
    return [
      content,
      transcriptJson,
    ]
  }
}

/// Response from structured generation
///
/// Generated class from Pigeon that represents data sent in messages.
struct StructuredResponseMessage {
  /// The generated content as JSON map
  var content: [String?: Any?]
  /// The raw GeneratedContent as JSON string
  var rawContent: String
  /// JSON-encoded transcript entries from this response
  var transcriptJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StructuredResponseMessage? {
    let content = pigeonVar_list[0] as! [String?: Any?]
    let rawContent = pigeonVar_list[1] as! String
    let transcriptJson = pigeonVar_list[2] as! String

    return StructuredResponseMessage(
      content: content,
      rawContent: rawContent,
      transcriptJson: transcriptJson
    )
  }
  func toList() -> [Any?] {
    return [
      content,
      rawContent,
      transcriptJson,
    ]
  }
}

private class FoundationModelsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SamplingModeType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModelUseCaseType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModelGuardrailsType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GenerationErrorType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return ToolDefinitionMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return SamplingModeMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return GenerationOptionsMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return ModelConfigurationMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return AdapterMessage.fromList(self.readValue() as! [Any?])
    case 138:
      return ModelAvailabilityMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return GenerationErrorMessage.fromList(self.readValue() as! [Any?])
    case 140:
      return TextResponseMessage.fromList(self.readValue() as! [Any?])
    case 141:
      return StructuredResponseMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FoundationModelsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SamplingModeType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModelUseCaseType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModelGuardrailsType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? GenerationErrorType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? ToolDefinitionMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? SamplingModeMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationOptionsMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ModelConfigurationMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? AdapterMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ModelAvailabilityMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationErrorMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? TextResponseMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? StructuredResponseMessage {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FoundationModelsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FoundationModelsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FoundationModelsApiPigeonCodecWriter(data: data)
  }
}

class FoundationModelsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FoundationModelsApiPigeonCodec(readerWriter: FoundationModelsApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FoundationModelsHostApi {
  /// Checks if Foundation Models API is available on this device.
  /// Returns true if iOS 26+ and the FoundationModels framework is available.
  func isAvailable() throws -> Bool
  /// Gets detailed availability information including reason if unavailable.
  func getModelAvailability() throws -> ModelAvailabilityMessage
  /// Creates an adapter. Returns adapter ID.
  /// Either name or assetPath must be provided.
  func createAdapter(name: String?, assetPath: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Destroys an adapter by ID.
  func destroyAdapter(adapterId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Creates a model with optional configuration.
  /// Returns a model ID.
  func createModel(configuration: ModelConfigurationMessage?, completion: @escaping (Result<String, Error>) -> Void)
  /// Destroys a model by ID.
  func destroyModel(modelId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Creates a session with the given model ID.
  func createSession(modelId: String, tools: [ToolDefinitionMessage], instructions: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Creates a session with an existing transcript (JSON encoded).
  func createSessionWithTranscript(modelId: String, tools: [ToolDefinitionMessage], transcriptJson: String, completion: @escaping (Result<String, Error>) -> Void)
  func destroySession(sessionId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Gets the transcript from a session as JSON.
  func getSessionTranscript(sessionId: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns whether the session is currently responding.
  func isSessionResponding(sessionId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Prewarms the session with an optional prompt prefix.
  func prewarmSession(sessionId: String, promptPrefix: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func respondTo(sessionId: String, prompt: String, options: GenerationOptionsMessage?, completion: @escaping (Result<TextResponseMessage, Error>) -> Void)
  /// Starts a text streaming response. Returns a stream ID.
  /// Updates will be sent via FlutterApi.onTextStreamUpdate.
  /// Completion will be sent via FlutterApi.onTextStreamComplete.
  func streamResponseTo(sessionId: String, prompt: String, options: GenerationOptionsMessage?, completion: @escaping (Result<String, Error>) -> Void)
  func respondToWithSchema(sessionId: String, prompt: String, schema: [String?: Any?], includeSchemaInPrompt: Bool, options: GenerationOptionsMessage?, completion: @escaping (Result<StructuredResponseMessage, Error>) -> Void)
  /// Starts a streaming response. Returns a stream ID.
  /// Snapshots will be sent via FlutterApi.onStreamSnapshot.
  /// Completion/error will be sent via FlutterApi.onStreamComplete/onStreamError.
  func streamResponseToWithSchema(sessionId: String, prompt: String, schema: [String?: Any?], includeSchemaInPrompt: Bool, options: GenerationOptionsMessage?, completion: @escaping (Result<String, Error>) -> Void)
  /// Cancels an active stream.
  func cancelStream(streamId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FoundationModelsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FoundationModelsApiPigeonCodec.shared }
  /// Sets up an instance of `FoundationModelsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FoundationModelsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Checks if Foundation Models API is available on this device.
    /// Returns true if iOS 26+ and the FoundationModels framework is available.
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    /// Gets detailed availability information including reason if unavailable.
    let getModelAvailabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.getModelAvailability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getModelAvailabilityChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getModelAvailability()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getModelAvailabilityChannel.setMessageHandler(nil)
    }
    /// Creates an adapter. Returns adapter ID.
    /// Either name or assetPath must be provided.
    let createAdapterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.createAdapter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createAdapterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg: String? = nilOrValue(args[0])
        let assetPathArg: String? = nilOrValue(args[1])
        api.createAdapter(name: nameArg, assetPath: assetPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createAdapterChannel.setMessageHandler(nil)
    }
    /// Destroys an adapter by ID.
    let destroyAdapterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.destroyAdapter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyAdapterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adapterIdArg = args[0] as! String
        api.destroyAdapter(adapterId: adapterIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroyAdapterChannel.setMessageHandler(nil)
    }
    /// Creates a model with optional configuration.
    /// Returns a model ID.
    let createModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.createModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg: ModelConfigurationMessage? = nilOrValue(args[0])
        api.createModel(configuration: configurationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createModelChannel.setMessageHandler(nil)
    }
    /// Destroys a model by ID.
    let destroyModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.destroyModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelIdArg = args[0] as! String
        api.destroyModel(modelId: modelIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroyModelChannel.setMessageHandler(nil)
    }
    /// Creates a session with the given model ID.
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelIdArg = args[0] as! String
        let toolsArg = args[1] as! [ToolDefinitionMessage]
        let instructionsArg: String? = nilOrValue(args[2])
        api.createSession(modelId: modelIdArg, tools: toolsArg, instructions: instructionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    /// Creates a session with an existing transcript (JSON encoded).
    let createSessionWithTranscriptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.createSessionWithTranscript\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionWithTranscriptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modelIdArg = args[0] as! String
        let toolsArg = args[1] as! [ToolDefinitionMessage]
        let transcriptJsonArg = args[2] as! String
        api.createSessionWithTranscript(modelId: modelIdArg, tools: toolsArg, transcriptJson: transcriptJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionWithTranscriptChannel.setMessageHandler(nil)
    }
    let destroySessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.destroySession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroySessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        api.destroySession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroySessionChannel.setMessageHandler(nil)
    }
    /// Gets the transcript from a session as JSON.
    let getSessionTranscriptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.getSessionTranscript\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSessionTranscriptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        api.getSessionTranscript(sessionId: sessionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSessionTranscriptChannel.setMessageHandler(nil)
    }
    /// Returns whether the session is currently responding.
    let isSessionRespondingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.isSessionResponding\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSessionRespondingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        api.isSessionResponding(sessionId: sessionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isSessionRespondingChannel.setMessageHandler(nil)
    }
    /// Prewarms the session with an optional prompt prefix.
    let prewarmSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.prewarmSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prewarmSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let promptPrefixArg: String? = nilOrValue(args[1])
        api.prewarmSession(sessionId: sessionIdArg, promptPrefix: promptPrefixArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      prewarmSessionChannel.setMessageHandler(nil)
    }
    let respondToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.respondTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let promptArg = args[1] as! String
        let optionsArg: GenerationOptionsMessage? = nilOrValue(args[2])
        api.respondTo(sessionId: sessionIdArg, prompt: promptArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondToChannel.setMessageHandler(nil)
    }
    /// Starts a text streaming response. Returns a stream ID.
    /// Updates will be sent via FlutterApi.onTextStreamUpdate.
    /// Completion will be sent via FlutterApi.onTextStreamComplete.
    let streamResponseToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.streamResponseTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      streamResponseToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let promptArg = args[1] as! String
        let optionsArg: GenerationOptionsMessage? = nilOrValue(args[2])
        api.streamResponseTo(sessionId: sessionIdArg, prompt: promptArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      streamResponseToChannel.setMessageHandler(nil)
    }
    let respondToWithSchemaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.respondToWithSchema\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondToWithSchemaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let promptArg = args[1] as! String
        let schemaArg = args[2] as! [String?: Any?]
        let includeSchemaInPromptArg = args[3] as! Bool
        let optionsArg: GenerationOptionsMessage? = nilOrValue(args[4])
        api.respondToWithSchema(sessionId: sessionIdArg, prompt: promptArg, schema: schemaArg, includeSchemaInPrompt: includeSchemaInPromptArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondToWithSchemaChannel.setMessageHandler(nil)
    }
    /// Starts a streaming response. Returns a stream ID.
    /// Snapshots will be sent via FlutterApi.onStreamSnapshot.
    /// Completion/error will be sent via FlutterApi.onStreamComplete/onStreamError.
    let streamResponseToWithSchemaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.streamResponseToWithSchema\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      streamResponseToWithSchemaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let promptArg = args[1] as! String
        let schemaArg = args[2] as! [String?: Any?]
        let includeSchemaInPromptArg = args[3] as! Bool
        let optionsArg: GenerationOptionsMessage? = nilOrValue(args[4])
        api.streamResponseToWithSchema(sessionId: sessionIdArg, prompt: promptArg, schema: schemaArg, includeSchemaInPrompt: includeSchemaInPromptArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      streamResponseToWithSchemaChannel.setMessageHandler(nil)
    }
    /// Cancels an active stream.
    let cancelStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsHostApi.cancelStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let streamIdArg = args[0] as! String
        api.cancelStream(streamId: streamIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelStreamChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FoundationModelsFlutterApiProtocol {
  func invokeTool(sessionId sessionIdArg: String, toolName toolNameArg: String, arguments argumentsArg: [String?: Any?], completion: @escaping (Result<[String?: Any?], PigeonError>) -> Void)
  /// Called when new text is available during text streaming.
  func onTextStreamUpdate(streamId streamIdArg: String, text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when text streaming completes successfully.
  func onTextStreamComplete(streamId streamIdArg: String, finalText finalTextArg: String, transcriptJson transcriptJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when a new snapshot is available during streaming.
  func onStreamSnapshot(streamId streamIdArg: String, partialContent partialContentArg: [String?: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when streaming completes successfully.
  func onStreamComplete(streamId streamIdArg: String, finalContent finalContentArg: [String?: Any?], rawContent rawContentArg: String, transcriptJson transcriptJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when streaming fails.
  func onStreamError(streamId streamIdArg: String, errorCode errorCodeArg: String, errorMessage errorMessageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FoundationModelsFlutterApi: FoundationModelsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FoundationModelsApiPigeonCodec {
    return FoundationModelsApiPigeonCodec.shared
  }
  func invokeTool(sessionId sessionIdArg: String, toolName toolNameArg: String, arguments argumentsArg: [String?: Any?], completion: @escaping (Result<[String?: Any?], PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsFlutterApi.invokeTool\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, toolNameArg, argumentsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [String?: Any?]
        completion(.success(result))
      }
    }
  }
  /// Called when new text is available during text streaming.
  func onTextStreamUpdate(streamId streamIdArg: String, text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsFlutterApi.onTextStreamUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when text streaming completes successfully.
  func onTextStreamComplete(streamId streamIdArg: String, finalText finalTextArg: String, transcriptJson transcriptJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsFlutterApi.onTextStreamComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, finalTextArg, transcriptJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when a new snapshot is available during streaming.
  func onStreamSnapshot(streamId streamIdArg: String, partialContent partialContentArg: [String?: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsFlutterApi.onStreamSnapshot\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, partialContentArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when streaming completes successfully.
  func onStreamComplete(streamId streamIdArg: String, finalContent finalContentArg: [String?: Any?], rawContent rawContentArg: String, transcriptJson transcriptJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsFlutterApi.onStreamComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, finalContentArg, rawContentArg, transcriptJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Called when streaming fails.
  func onStreamError(streamId streamIdArg: String, errorCode errorCodeArg: String, errorMessage errorMessageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_foundation_models.FoundationModelsFlutterApi.onStreamError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, errorCodeArg, errorMessageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
